<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style/main.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSV-viewer</title>
</head>
<body>

    <p>
    You can upload csv file containing name and phone columns and press the "Show data" button.
    <br>
    It'll display data on the current page.
    </p>
    <table>
        <form action="src/parse.php" method="post" enctype="multipart/form-data">
        <tr>
            <td width="20%">Select csv file</td>
            <td width="80%"><input type="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" name="file" id="file" /></td>
        </tr>
        <tr>
            <td>Submit</td>
            <td><input type="submit" name="submit" value="Show data" /></td>
        </tr>
        </form>
    </table>

<?php if ($_GET['status'] == 'empty'): ?>
            <?= "<p>Please select a csv file first</p>" ?>
        <?php  elseif ($_GET['errors'] > 0): ?>
            <?= "<p>Sorry, there was some error, please try again</p>" ?>
<?php endif ?>

<?php $users = json_decode(file_get_contents(__DIR__ . '/data/storage.json'), true); ?>
<?php if(isset($users)) : ?>
    <table id="users">
    <?php foreach ($users as $user) : ?>
        <tr style="background-color: <?= $user['color'] ?>">
            <td><?= $user['name'] ?></td>
            <td><?= $user['phone'] ?></td>
        </tr>
    <?php endforeach ?>
<table>
<?php endif ?>
</body>
